### ISSUE TITLE
BUG [swscaler...]Warning: Data is not aligned!...

### ISSUE THREAD

**Issue by Nekuake** [namkazt/PinBox#11]
## Expected Behavior
The stream shouldn't show any error.

## Current Behavior
The console shows an error:  [swscaler @ <number>] Warning: Data is not aligned! This can lead to a speed loss. 
It can be due to an scale error according to [a ffmpeg Pipeline](https://ffmpeg.org/pipermail/ffmpeg-user/2017-October/037501.html).

## Possible Solution
There are a lot of possible solutions. One is changing the image format or the pixel format. Other is making sure that final dimensions are multiples of 8, 16 or 32. Also, FFmpeg says that the codec may be deprecated and they reccomend to use AVStream.codecpar instead.

## Steps to Reproduce
1. Just initialize an stream

**Comment by namkazt** [comment]
my plan was change final image size to 512x256, so we do not extra step to convert on 3ds side.

**Comment by Nekuake** [comment]
According to FFMPEG, that would solve the problem.

**Comment by imyetihearmeroar** [comment]
I have the exact same problem, what are the exact steps I should take to fix this?
also, the dicord link doesn't work anymore.

**Comment by jerielbg** [comment]
Bonjour ,
Comment ont initialise le flux

**Comment by ExperiencersInternational** [comment]
I'm experiencing the same problem as well, I know this is no longer worked on but is there any forks that don't have this issue @namkazt.

I'm using an old 3DS and it's really annoying.

**Comment by Nekuake** [comment]
If this was not fixed in 2018, I wouldn't expect it in 2022.

**Comment by LavaRed** [comment]
> If this was not fixed in 2018, I wouldn't expect it in 2022.

:(

**Comment by XDcodingBTW** [comment]
> my plan was change final image size to 512x256, so we do not extra step to convert on 3ds side.



> my plan was change final image size to 512x256, so we do not extra step to convert on 3ds side.

how do you do that

**Comment by XDcodingBTW** [comment]
> my plan was change final image size to 512x256, so we do not extra step to convert on 3ds side.

how do you do that
