### ISSUE TITLE
[Project Maintenance] Update Discord Server Link

### ISSUE THREAD

**Issue by MoXAriApph** [namkazt/PinBox#19]
Current link does not work.

**Comment by kibiz0r** [comment]
Try this: https://discord.gg/6yDWpqXVJ9

There are some breadcrumbs across the web: https://www.reddit.com/r/Guildwars2/comments/r1h0xx/guide_gw2_on_a_2ds_or_3ds_related_consoles/ and https://gbatemp.net/threads/pinbox-desktop-remote-streaming.493302/page-6#post-9666942

There's also a repo for a v2 of PinBox, called Mirror, but bear in mind that this is a one-person operation for a niche project, so development is likely to be sporadic and eventually die out for good: https://github.com/namkazt/Mirror-3DS

**Comment by MoXAriApph** [comment]
You linked my own post back to me lol
