### ISSUE TITLE
Request: Standardize Numpad Format

### ISSUE THREAD

**Issue by Mauville** [namkazt/PinBox#6]
Currently, the NumPad format for the 3DS app is non-standard, sometimes making the inputting of the IP clumsy:
0 1 2
3 4 5
6 7 8 
. 9 :

I suggest changing it to a more standardized version such as 

1 2 3
4 5 6
7 8 9
. 0 ,

**Comment by namkazt** [comment]
changed to
1 2 3
4 5 6
7 8 9
. 0 :
