### ISSUE TITLE
Lost frames add delay to the stream.

### ISSUE THREAD

**Issue by Nekuake** [namkazt/PinBox#8]
Would it be possible to skip the lost frames instead of waiting for them? I have tweaked the options and it still does the same.
3DS settings:
"Quality" is set to 10, "scale" is set to 10, "skip frame" is set to 10 and "wait received" is set to off.
Server settings:
monitor_index= 0, capture_fps= 15, network_threads=4, server_port=1234

**Comment by namkazt** [comment]
current verison was got delay because of wait for audio frame. capture fps
should be 30 fps and netowkr thread only should be around 2.





*
              Best Regards.Mr. Nam NguyễnPhone No. : 012.9595.8685*

*Skype Account : nam.kazt*

**Comment by Nekuake** [comment]
I will wait for it! But the problem occured also in the previous version, the one without audio streaming.

**Comment by namkazt** [comment]
skip frame is a feature that i will introduce in next version, together with apply video setting mode before start stream.
check on #dev-logs channel for more information
